DELETE http://localhost:8080/api/cart/clear　


###

POST http://localhost:8080/api/cart
Content-Type: application/json

{"productId": 1, "quantity": 4}

###


PUT http://localhost:8080/api/cart/items/1
Content-Type: application/json

{"quantity": 5}